services:
  bot:
    build: .
    command: python -m bot.main
    environment:
      REDIS_CLIENT_HOST: redis
      REDIS_CLIENT_PORT: 6379
      DB_HOST: pg
      DB_PORT: 5432
      DB_NAME: weather_bot_db
      DB_USER: postgres
      DB_PASSWORD: root
    depends_on:
      - redis

  taskiq-worker:
    build: .
    command: taskiq worker bot.tasks.broker:broker
    environment:
      REDIS_CLIENT_HOST: redis
      REDIS_CLIENT_PORT: 6379
      DB_HOST: pg
      DB_PORT: 5432
      DB_NAME: weather_bot_db
      DB_USER: postgres
      DB_PASSWORD: root
    depends_on:
      - redis

  taskiq-scheduler:
    build: .
    command: taskiq scheduler bot.tasks.broker:scheduler --skip-first-run --update-interval 5
    environment:
      REDIS_CLIENT_HOST: redis
      REDIS_CLIENT_PORT: 6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data:
